 var favoriteDrink = "green tea";
favoriteDrink;
console.log(favoriteDrink);
var favoriteNumber =42;
favoriteNumber +=1;
console.log(favoriteNumber);
var myNumber = 3;
console.log(myNumber < 5);
console.log(myNumber >5);
console.log(myNumber === 3);
console.log(myNumber === 4);
var firstNumber =27;
var secondNumber =42;
console.log(firstNumber >secondNumber);
console.log(firstNumber <secondNumber);
console.log(firstNumber === secondNumber);
console.log(firstNumber +=15); 
console.log(secondNumber -=10);
var nn="67";
var yy = 57;
console.log(nn === yy); 
var m= prompt("What is your favorite planet?") // I'm going to type "Earth"
console.log(m);
var x= alert("Hey there!");
console.log(x);
var u= prompt("Are you ready to code?").toUpperCase();
console.log(u);
var b=confirm("Would you like to continue?");
console.log(b);

